
resources:
  containers:
  - container: myACRContainer  
    type: ACR
    azureSubscription: raireg1
    resourceGroup: raiyan-rg2
    registry: 'raireg1.azurecr.io'
    repository: zenithworksazurevotingappredis

resources:
  containers:
  - container: ACRRes
    type: ACR
    azureSubscription: azrm
    resourceGroup: gykuma-RG
    registry: gykumaacr
    repository: hello-world

variables:
  system.debug: 'true'


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: 'igniteDemo'
    steps:
    - script:
        echo "Hello world"
