
resources:
  containers:
  - container: myACRContainer  
    type: ACR
    azureSubscription: RMPM
    resourceGroup: raiyan-rg2
    registry: raireg1
    repository: zenithworksazurevotingappredis
    trigger: true


variables:
  system.debug: 'true'


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: 'igniteDemo'
    steps:
    - script:
        echo "Hello world"
