trigger: none

resources:
- repo: self

variables:

  system.debug: 'true'
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'raireg1'
  imageRepository: 'zenithworksazurevotingappredis'
  containerRegistry: 'raireg1.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'raireg11795044f-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: 'igniteDemo'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool: 'igniteDemo'
    environment: 'zenithworksazurevotingappredis.ignitedemo1'
    strategy:
      canary:
        increments: [25]
        preDeploy:
          steps:
          - script:
              echo $(strategy.name)
        deploy:
          steps:
          - script: |
              echo Strategy: $(strategy.name)
              echo Increment: $(strategy.increment)

          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
           #   kubernetesServiceConnection: ''
              namespace: 'default'
              strategy: $(strategy.name)
              percentage: $(strategy.increment)
              manifests: 'manifests/deployment.yml'
              imagePullSecrets: ''
        postRouteTraffic:
          pool: server
          steps:
            - task: Delay@1
              inputs:
                delayForMinutes: '2'
        on:
          failure:
            steps:
            - script: echo deployment failed...
            - task: KubernetesManifest@0
              inputs:
                action: 'reject'
               # kubernetesServiceConnection: ''
                namespace: 'default'
                strategy: $(strategy.name)
                manifests: 'manifests/deployment.yml'
          success:
            steps:
            - script: echo deployment succeeded...              
            - task: KubernetesManifest@0 
              inputs:
                action: 'promote'
               # kubernetesServiceConnection: ''
                namespace: 'default'
                strategy: $(strategy.name)
                manifests: 'manifests/deployment.yml'
