
resources:
  containers:
  - container: myACRContainer  
    type: ACR
    subscription: RMPM
    registry: 'raireg1.azurecr.io'
    image: zenithworksazurevotingappredis



variables:
  system.debug: 'true'
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'raireg1'
  imageRepository: 'zenithworksazurevotingappredis'
  containerRegistry: 'raireg1.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'raireg11795044f-auth'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: 'igniteDemo'
    steps:
    - script:
        echo "Hello world"
