trigger: none 
pr: none


resources:
  containers:
  - container: myACRContainer2  
    type: ACR
    azureSubscription: 'RMPM'
    resourceGroup: raiyan-rg2
    registry: raireg1
    repository: zenithworksazurevotingappredis
    trigger: true


variables:
  system.debug: 'true'


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: 'demopool'
    steps:
    - task: Powershell@2
      inputs:
        targetType: inline
        script: |
          echo hello world
          #Write-Host $(resources.container.myACRContainer.type)
          #Write-Host $(resources.container.myACRContainer.registry)
          #Write-Host $(resources.container.myACRContainer.repository)
          #Write-Host $(resources.container.myACRContainer.tag)
          #Write-Host $(resources.container.myACRContainer.digest)
          #Write-Host $(resources.container.myACRContainer.location)
