# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: BuildAndPushToACR

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'raireg1'
  imageRepository: 'zenithworksazurevotingappredis'
  containerRegistry: 'raireg1.azurecr.io'
  dockerfilePath: '/azure-vote/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'raireg13255727b-auth'

  # Agent VM image name
  vmImageName: 'RaiAgents'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: 'RaiAgents'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: '$(tag)'
