
resources:
  containers:
  - container: myACRContainer  
    type: ACR
    subscription: RMPM
    resourceGroup: raiyan-rg2
    registry: 'raireg1.azurecr.io'
    repository: zenithworksazurevotingappredis



variables:
  system.debug: 'true'


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: 'igniteDemo'
    steps:
    - script:
        echo "Hello world"
