jobs:
- deployment:
  environment: PepsiProd.igniteDemo1
  pool: demopool
  strategy:                 
    canary:     
      increments: [10,20] 
      preDeploy:                                           
        steps:          
        - script: |
            echo StrategyName: $(strategy.name)
      deploy:
        steps:
        - script: |
            echo Deploy: $(strategy.increment)
            echo StrategyName: $(strategy.name)
      routeTraffic:
        steps:
        - script: |
            echo routeTraffic: $(strategy.increment)
            echo StrategyName: $(strategy.name)
      on:
        failure:
          steps:
          - script: |
              echo StrategyName: $(strategy.name)
        success:
          steps:
          - script: |
              echo StrategyName: $(strategy.name)
