trigger: none
stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: VMDeploy
    displayName: Deploy to VM job
    pool: igniteDemo
    environment:
      name: Rai-VM-Env
      resourceType: VirtualMachine
    strategy:
      rolling:
        maxBatchSize: 2
        deploy:
          steps:
            - script: echo Hello, world! This is deploy
              displayName: 'Run a one-line script'